server.port=8080

# Correct Atlas URI - NO trailing quote
spring.data.mongodb.uri=mongodb+srv://pankajnaik297_db_user:pankaj297mongo@cluster0.rfcf5el.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=shaadi_db



# Cloudinary
cloudinary.cloud-name=deb8xlfto
cloudinary.api-key=382517336861377
cloudinary.api-secret=htl04GLVJeAe_joUJTX9sMFk-EQ

# multipart
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Debugging
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.mongodb.driver=INFO
