# ===============================
# Server
# ===============================
server.port=8080

# ===============================
# MongoDB Atlas Configuration cloud password = pankaj@1807
# ===============================
spring.data.mongodb.uri=mongodb+srv://shaadi-pankaj:MaGps5hpB0IfgWP3@shaadi.benp5nu.mongodb.net/shaadi_db?retryWrites=true&w=majority

spring.data.mongodb.database=shaadi_db

# ===============================
# Cloudinary Configuration
# ===============================
cloudinary.cloud-name=deb8xlfto
cloudinary.api-key=382517336861377
cloudinary.api-secret=htl04GLVJeAe_joUJTX9sMFk-EQ

# ===============================
# Multipart (File Upload)
# ===============================
spring.servlet.multipart.max-file-size=4MB
spring.servlet.multipart.max-request-size=4MB

# ===============================
# Mongo Debug (Optional)
# ===============================
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.mongodb.driver=INFO
